# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('desc', models.TextField()),
                ('category', models.CharField(default='Undefined', max_length=50)),
                ('sex', models.BinaryField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
            ],
        ),
    ]
