# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200113_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], null=True),
        ),
    ]
