# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200113_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
