# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200116_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='people',
            field=models.ManyToManyField(blank=True, to='main.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.Category'),
        ),
    ]
